from __future__ import annotations

from enum import StrEnum


class AuditEventType(StrEnum):
    """
    Enumeration of all audit events generated by the
    AI Compliance Engine.
    """

    #
    # Configuration
    #
    CONFIGURATION_LOADED = "CONFIGURATION_LOADED"

    #
    # Holdings
    #
    HOLDINGS_LOADED = "HOLDINGS_LOADED"

    #
    # Graph
    #
    GRAPH_CONSTRUCTED = "GRAPH_CONSTRUCTED"

    #
    # Computation
    #
    COMPUTATION_STARTED = "COMPUTATION_STARTED"

    COMPUTATION_COMPLETED = "COMPUTATION_COMPLETED"

    #
    # Traceability
    #
    TRACEABILITY_ATTACHED = "TRACEABILITY_ATTACHED"

    #
    # Reconciliation
    #
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"

    RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED"

    #
    # Narrative
    #
    NARRATIVE_GENERATION_STARTED = (
        "NARRATIVE_GENERATION_STARTED"
    )

    NARRATIVE_GENERATED = (
        "NARRATIVE_GENERATED"
    )

    #
    # Report
    #
    REPORT_GENERATION_STARTED = (
        "REPORT_GENERATION_STARTED"
    )

    REPORT_GENERATED = (
        "REPORT_GENERATED"
    )

    #
    # System
    #
    APPLICATION_STARTED = "APPLICATION_STARTED"

    APPLICATION_SHUTDOWN = "APPLICATION_SHUTDOWN"

    ERROR = "ERROR"


class AuditStatus(StrEnum):
    """
    Audit event execution status.
    """

    SUCCESS = "SUCCESS"

    FAILED = "FAILED"

    WARNING = "WARNING"

    INFO = "INFO"